### ISSUE TITLE
Оptimization Draw Modes

### ISSUE THREAD

**Issue by kerenska** [CorpGlory/grafana-graph-panel#12]
Hello, we use this type of panel in bars draw modes. But since I want to see two or more series, it would be more convenient if there is side by side mode options. Тhis is for the new version v7.0.3, since there is none in it Multibar Graph Panel.

**Comment by jonyrock** [comment]
Helllo. Related issue: https://github.com/CorpGlory/grafana-multibar-graph-panel/issues/51
At this point I can't say much about the 7.0.3, but there is https://github.com/chartwerk/grafana-chartwerk-panel which can render multibars somehow in grafana 7

**Comment by kerenska** [comment]
Yes, I know it. But Chartwerk Panel have is a very short interval for data visualization- from max 60 min. 
For example we need from 1 day. 
That's why I have a suggestion for optimizing the Graph panel, to have mode options bar side by side.

**Comment by corpglory-dev** [comment]
Hi @kerenska,

There is time interval issue in the Chartwerk panel repo: https://github.com/chartwerk/grafana-chartwerk-panel/issues/44. You can subscribe to know when it's fixed.

**Comment by corpglory-dev** [comment]
Hi @kerenska,

Time interval is fully configurable in new version of Chartwerk panel: https://github.com/chartwerk/grafana-chartwerk-panel/releases/tag/0.1.2
