### ISSUE TITLE
New features for chartwerk 

### ISSUE THREAD

**Issue by kerenska** [CorpGlory/grafana-graph-panel#14]
Whether to add functionality to the axes, such as Right Y, Unit, Scale, Decimals?
Also whether there will be a possibility for color correction of the series?

**Comment by jonyrock** [comment]
Hey @kerenska, thnak you for your request. 
This repo exists as an attempt to provide developers a way to build their plugins. 
We don't support new features here and it haven't ever been a goal of this project. 
I encourage to use https://github.com/chartwerk/grafana-chartwerk-panel which is designed for advanced visualizations and has graph chart there. So the best way to get this feature is to make issue in the right repo.
