### ISSUE TITLE
different series stacked on each other.

### ISSUE THREAD

**Issue by singhmeghna79** [CorpGlory/grafana-graph-panel#3]
Hi,
I have cloned this repo and using this graph plugin. I am showing capacity graph.
I have two queries one for getting used volume and another for getting total volumes . But the problem is when i select X-axis mode as  'series'  then  total volume  is not stacked on used volume. I have muti-select templating enabled so at a time if i select two volumes then total 4 bars are shows( two for 1st volume{used and total} and two for 2nd {used and total}).
But i want used and total to be stacked on each other. Is there a way for doing this? i need help its urgent.

**Comment by rozetko** [comment]
Hi @Meghna-singh! Sorry for waiting. Actually, it's just a built-in Grafana plugin taken out of Grafana repo to make it easier to hack. So we can't answer your question, unfortunately. It would be much more effective if you ask it in original Grafana repo: https://github.com/grafana/grafana/issues

**Comment by singhmeghna79** [comment]
thanks
